package:
    name: pandas
    version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('.dev', 'dev') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
    git_url: ../
    git_tag: test-conda

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools
    - pytz
    - python-dateutil

  run:
    - python
    - numpy x.x
    - python-dateutil
    - pytz

#test:
#  imports:
#    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD
